services:
  ubuntu24-oqs:
    image: openca.org/ubuntu24-oqs:latest
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - type: bind
        source: ${PWD}
        target: /workspace
    stdin_open: true
    tty: true
