version: "1.0"
services:
  centos7:
    image: openca.org/dev/centos7:latest
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8080:8080"
    volumes:
      - type: bind
        source: ${PWD}
        target: /workspace
    environment:
      - API_BASE_URL=${API_BASE_URL}
    stdin_open: true
    tty: true
networks:
  default:
    name: dev-network
