# Docker ubuntu24 (base)
alias "ubuntu24-up"="docker compose -f ~/.dockercompose/docker-compose-ubuntu24.yml -p dev up -d"
alias "ubuntu24-down"="docker compose -p dev down"
alias "ubuntu24-bash"="docker exec -it dev-ubuntu24-1 /bin/bash"

# Docker ubuntu24-crypto (base)
alias "ubuntu24-crypto-up"="docker compose -f ~/.dockercompose/docker-compose-ubuntu24-crypto.yml -p dev up -d"
alias "ubuntu24-crypto-down"="docker compose -p dev down"
alias "ubuntu24-crypto-bash"="docker exec -it dev-ubuntu24-crypto-1 /bin/bash"

# Docker ubuntu-libpki (libpki)
alias "ubuntu24-libpki-up"="docker compose -f ~/.dockercompose/docker-compose-ubuntu24-libpki.yml -p dev up -d"
alias "ubuntu24-libpki-down"="docker compose -p dev down"
alias "ubuntu24-libpki-bash"="docker exec -it dev-ubuntu24-libpki-1 /bin/bash"
